### ISSUE TITLE
unable to edit text while replaying

### ISSUE THREAD

**Issue by codesiddhant** [rrweb-io/rrweb-player#78]
I want to edit the text fields after pausing the video !! 
just like scrimba.com 
where whenever the user wants to edit the text builds, he just pauses the video and makes changes in the middle.
when playing he again plays the video text field should be reset as before pausing the video..

**Comment by Juice10** [comment]
You can do that by allowing your iframe to be interactive. To do that you can add this css to your page:

```css
.rr-player iframe {
  pointer-events: initial !important;
}
```
